Homework 06
Otus-DevOps-2017-11/reddare_infra pull request #2
Opened 2017-12-17 19:47 UTC by reddare

Homework 06 added

2017-12-19 09:56 UTC, Nklya reviewed
Добрый день.

Антон, условия дз более-менее выполнены, подготовка и деплой корректные почти полностью, кроме скрипта gcp_startup.sh.

Приведенная тобой команда запуска инстанса из ридми не работает, т.к. приложение деплоится без БД и соответственно оно нерабочее.

Замечания:
1. Собственно нужно поправить gcp_startup.sh чтобы команда из ридми корректно создавала инстанс с приложением.
2. Я в прошлом дз еще писал, что ты закоммитил нерабочий скрипт setupvpn.sh. Он в таком виде и остался. Необходимо его скопировать нормально из слайдов предыдущего дз.
3. Перенеси все что делалось в пред. дз в директорию `VPN`
4. Ну и помимо startup-script-url нужно добавить в ридми пример с startup-script

2017-12-19 09:56 UTC, Nklya commented on README.md
> +--metadata "startup-script-url=https://storage.googleapis.com/reddare-infra/gcp_startup.sh"
Помимо startup-script-url нужно добавить в ридми пример с startup-script

2017-12-19 09:56 UTC, Nklya commented on gcp_startup.sh
> +sudo apt install -y mongodb-org
Как здесь будет работать установка монги, если ты не сделал `apt update` после добавления репы монги?

2017-12-19 09:57 UTC, Nklya requested changes
Собственно после исправления повторное ревью.
Фиксить можно коммитами в бранч Infra-2, PR закрывать или создавать новый не нужно.

2017-12-22 16:09 UTC, reddare commented
Поправил все ошибки. Проверьте пожалуйста.

2017-12-24 12:20 UTC, Nklya approved these changes
Добрый день.

Антон, условия дз выполнены, подготовка и деплой корректные.

Замечания я оставил ниже.

2017-12-24 12:20 UTC, Nklya commented on README.md
> +--metadata "startup-script-url=https://storage.googleapis.com/reddare-infra/gcp_startup.sh"
А почему скрипт по этому урлу старый, который нерабочий?

2017-12-24 12:20 UTC, Nklya commented on README.md
> +gcloud startup script
Зачем указывать скрипт в ридми, если он уже закоммичен?

2017-12-24 12:20 UTC, Nklya commented on VPN/setupvpn.sh
>  apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv
Здесь тоже перенос строки лишний

2017-12-24 12:20 UTC, Nklya commented on VPN/setupvpn.sh
>  apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv
Здесь тоже перенос строки лишний

2017-12-24 12:20 UTC, Nklya commented on README.md
> +--metadata "startup-script-url=https://storage.googleapis.com/reddare-infra/gcp_startup.sh"
Поменяй просто эту строчку на `--metadata-from-file startup-script=gcp_startup.sh` и не надо будет забирать скрипт с урла

2017-12-24 12:58 UTC, reddare commented on README.md
> +--metadata "startup-script-url=https://storage.googleapis.com/reddare-infra/gcp_startup.sh"
Забыл загрузить исправленный в бакет. Поправил.

2017-12-24 12:58 UTC, reddare commented on README.md
> +--metadata "startup-script-url=https://storage.googleapis.com/reddare-infra/gcp_startup.sh"
Ок. Сделал.

2017-12-24 12:59 UTC, reddare commented on README.md
> +gcloud startup script
Не правильно понял 4 пункт из прошлого ревью. Убрал.

2017-12-24 12:59 UTC, reddare commented on VPN/setupvpn.sh
>  apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv
Исправил.

2017-12-24 13:00 UTC, reddare commented on VPN/setupvpn.sh
>  apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv
Исправил.

2017-12-24 13:03 UTC, merged