Homework 07
Otus-DevOps-2017-11/reddare_infra pull request #3
Opened 2017-12-24 12:43 UTC by reddare

Homework 07 added

2017-12-25 11:46 UTC, vitkhab requested changes
Выполнено все очень и очень хорошо.

Прошу доработать файл `variables.json.example`

Документация минимальна, но достаточна. Пример куда можно развиваться - https://goo.gl/me4MEX

Из плюсов:
- Вижу оба дополнительных задания выполнены. Молодец!
- Вижу интересовался `googlecompute builder`'ом. Тоже круто!

2017-12-25 11:46 UTC, vitkhab commented on packer/variables.json.example
> + "tags": ["network_tag"]
При значении по умолчанию, получаю ошибку
```
invalid value "variables.json" for flag -var-file: Error reading variables in 'variables.json': json: cannot unmarshal array into Go value of type string
```

А если убрать скобки, то ошибку
```
==> googlecompute: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.tags.items[0]': 'network_tag'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```

2017-12-25 20:54 UTC, reddare commented
Минимализм в ридми - детская травма с тех времен, когда взрослые дядьки линуксойды тыкали в rtfm. Но если вам действительно поможет избыточность информации о совершенном ДЗ, то окей, исправлюсь.

2017-12-25 20:54 UTC, reddare commented on packer/variables.json.example
> + "tags": ["network_tag"]
Поправил, можно проверять.

2017-12-27 10:19 UTC, vitkhab approved these changes

2017-12-27 10:21 UTC, vitkhab commented
Для завершения ДЗ документации хватает. Потому это не требование, а предложение. Наша цель научиться работать хорошо.
Документация сильно помогает людям совсем незнакомым с проектом или технологией. Это важно для open source проектов, где любой прохожий может воспользоваться твоими наработками.

2017-12-27 12:31 UTC, merged